### ISSUE TITLE
/entrypoint.sh: line 62: syntax error: unexpected "(" with v1.1

### ISSUE THREAD

**Issue by RoFz** [mdegis/bandit-action#7]
I'm working on a PR so that this action could support GHES via the GITHUB_API_URL variable instead of the static API URL in formatter.py, but came up with the following error with the latest release.

When using v1.1:

```
      - uses: mdegis/bandit-action@v1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: 'components/hello-world'
          level: low
          confidence: low
```

I get this:

```
/entrypoint.sh: line 62: syntax error: unexpected "("
```

Version 1.0 works fine.

Is the error above expected with v1.1 or am I missing something in my config?

**Comment by nandgator** [comment]
I could reproduce this:

https://github.com/python-validators/validators/actions/runs/8354135019/job/22866991249?pr=337#step:4:13

Previous commit

```
uses: mdegis/bandit-action@85fcc340c3b0bf5d86029abb49b9aac916d807b2
```

works fine.

**Comment by ferrarijefferson** [comment]
The issue with the shell script is that it's trying to access the array "$1" as if it were a matrix, but in reality, it's just a command-line argument. In a shell script, $1 refers to the first argument passed to the script, $2 to the second argument, and so on.

This should solve the problem. I tried to open a PR but didn't have permissions.

```shell
unique_directories=($(printf "%s\n" "${@:1}" | sort -u))

for dir in "${unique_directories[@]}"; do
    bandit -r $dir $LEVEL $CONFIDENCE $EXCLUDED_PATHS $EXIT_ZERO $SKIPS $INI_PATH
done
```

**Comment by huyz** [comment]
There is a PR that includes the fix: https://github.com/mdegis/bandit-action/pull/8

**Comment by mpounsett** [comment]
This is still an issue.  I can confirm that using mdegis/bandit-action@v1.0.1 is fine.

**Comment by mpounsett** [comment]
1.0.1 is now failing with the unexpected `pbr` import, so bandit-action is now unusable
